env:
  browser: true
  node: true
  es2021: true

plugins:
  - security
  - security-node
  - no-unsanitized

rules:
  security/detect-buffer-noassert: warn
  security/detect-child-process: warn
  security/detect-disable-mustache-escape: warn
  security/detect-eval-with-expression: error
  security/detect-new-buffer: warn
  security/detect-no-csrf-before-method-override: warn
  security/detect-non-literal-fs-filename: warn
  security/detect-non-literal-regexp: warn
  security/detect-non-literal-require: warn
  security/detect-object-injection: warn
  security/detect-possible-timing-attacks: warn
  security/detect-pseudoRandomBytes: warn
  security-node/detect-crlf: warn
  security-node/detect-disable-x-powered-by: warn
  security-node/detect-exposed-headers: warn
  security-node/detect-insecure-cookies: warn
  security-node/detect-insecure-jwt-sign: warn
  no-unsanitized/method: warn
  no-unsanitized/property: warn
